from __future__ import annotations

import json
import os
from urllib import request

from sdt_bench.schemas import AgentContext, PatchProposal


class OpenAILikeAdapter:
    name = "openai_like"

    def __init__(self) -> None:
        self.base_url = os.environ.get("SDT_BENCH_OPENAI_LIKE_BASE_URL", "").rstrip("/")
        self.api_key = os.environ.get("SDT_BENCH_OPENAI_LIKE_API_KEY", "")
        self.model = os.environ.get("SDT_BENCH_OPENAI_LIKE_MODEL", "")

    @property
    def configured(self) -> bool:
        return bool(self.base_url and self.api_key and self.model)

    def generate_patch(self, context: AgentContext) -> PatchProposal:
        citations = sorted({chunk.source_path for chunk in context.retrieved_chunks})
        if not self.configured:
            return PatchProposal(
                episode_id=context.episode.episode_id,
                patch_text="",
                citations_used=citations,
                summary="OpenAI-like adapter not configured; emitted a no-op patch.",
            )

        prompt = {
            "task_prompt": context.task_prompt,
            "visible_failure_signal": context.visible_failure_signal,
            "retrieved_chunks": [chunk.model_dump(mode="json") for chunk in context.retrieved_chunks],
            "workspace": context.workspace,
        }
        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": "Return only a unified diff patch. Emit an empty string if no code change is required.",
                },
                {"role": "user", "content": json.dumps(prompt)},
            ],
        }
        body = json.dumps(payload).encode("utf-8")
        req = request.Request(
            url=f"{self.base_url}/chat/completions",
            data=body,
            headers={"Content-Type": "application/json", "Authorization": f"Bearer {self.api_key}"},
            method="POST",
        )
        with request.urlopen(req, timeout=60) as response:
            result = json.loads(response.read().decode("utf-8"))
        patch_text = result["choices"][0]["message"]["content"]
        return PatchProposal(
            episode_id=context.episode.episode_id,
            patch_text=patch_text,
            citations_used=citations,
            summary="Patch generated by OpenAI-like adapter.",
        )
